version: '3.8'

services:
  grpc-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        DB_PATH: ${DB_PATH:-database.db}
    ports:
      - "50051:50051"
    env_file:
      - .env
    container_name: go-grpc-server-dev
    volumes:
      - ./backend:/app
      - /app/bin


