// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RatingCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatingCategory) Reset() {
	*x = RatingCategory{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatingCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatingCategory) ProtoMessage() {}

func (x *RatingCategory) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatingCategory.ProtoReflect.Descriptor instead.
func (*RatingCategory) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *RatingCategory) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RatingCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RatingCategory) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CategoryScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	RatingCount   int32                  `protobuf:"varint,4,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryScore) Reset() {
	*x = CategoryScore{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryScore) ProtoMessage() {}

func (x *CategoryScore) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryScore.ProtoReflect.Descriptor instead.
func (*CategoryScore) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryScore) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryScore) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CategoryScore) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *CategoryScore) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type DailyAggregatedScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*CategoryScore       `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyAggregatedScoresResponse) Reset() {
	*x = DailyAggregatedScoresResponse{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyAggregatedScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyAggregatedScoresResponse) ProtoMessage() {}

func (x *DailyAggregatedScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyAggregatedScoresResponse.ProtoReflect.Descriptor instead.
func (*DailyAggregatedScoresResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *DailyAggregatedScoresResponse) GetScores() []*CategoryScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *DailyAggregatedScoresResponse) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *DailyAggregatedScoresResponse) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type WeeklyAggregatedScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*CategoryScore       `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeeklyAggregatedScoresResponse) Reset() {
	*x = WeeklyAggregatedScoresResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyAggregatedScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyAggregatedScoresResponse) ProtoMessage() {}

func (x *WeeklyAggregatedScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyAggregatedScoresResponse.ProtoReflect.Descriptor instead.
func (*WeeklyAggregatedScoresResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *WeeklyAggregatedScoresResponse) GetScores() []*CategoryScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *WeeklyAggregatedScoresResponse) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *WeeklyAggregatedScoresResponse) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type AggregatedCategoryScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedCategoryScoresRequest) Reset() {
	*x = AggregatedCategoryScoresRequest{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedCategoryScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedCategoryScoresRequest) ProtoMessage() {}

func (x *AggregatedCategoryScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedCategoryScoresRequest.ProtoReflect.Descriptor instead.
func (*AggregatedCategoryScoresRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *AggregatedCategoryScoresRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *AggregatedCategoryScoresRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ScoresByTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoresByTicketRequest) Reset() {
	*x = ScoresByTicketRequest{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoresByTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoresByTicketRequest) ProtoMessage() {}

func (x *ScoresByTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoresByTicketRequest.ProtoReflect.Descriptor instead.
func (*ScoresByTicketRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *ScoresByTicketRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ScoresByTicketRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14category_score.proto\x1a\x12ticket_score.proto\x1a\x1boverall_quality_score.proto\x1a\x18period_over_period.proto\"L\n" +
	"\x0eRatingCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\"\xbe\x01\n" +
	"\rCategoryScore\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12!\n" +
	"\frating_count\x18\x04 \x01(\x05R\vratingCount\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xc3\x01\n" +
	"\x1dDailyAggregatedScoresResponse\x120\n" +
	"\x06scores\x18\x01 \x03(\v2\x18.analytics.CategoryScoreR\x06scores\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xc4\x01\n" +
	"\x1eWeeklyAggregatedScoresResponse\x120\n" +
	"\x06scores\x18\x01 \x03(\v2\x18.analytics.CategoryScoreR\x06scores\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x93\x01\n" +
	"\x1fAggregatedCategoryScoresRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x89\x01\n" +
	"\x15ScoresByTicketRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate2\xbf\x03\n" +
	"\x10AnalyticsService\x12v\n" +
	"\x1bGetAggregatedCategoryScores\x12*.analytics.AggregatedCategoryScoresRequest\x1a+.analytics.AggregatedCategoryScoresResponse\x12X\n" +
	"\x11GetScoresByTicket\x12 .analytics.ScoresByTicketRequest\x1a!.analytics.ScoresByTicketResponse\x12g\n" +
	"\x16GetOverallQualityScore\x12%.analytics.OverallQualityScoreRequest\x1a&.analytics.OverallQualityScoreResponse\x12p\n" +
	"\x19GetPeriodOverPeriodChange\x12(.analytics.PeriodOverPeriodChangeRequest\x1a).analytics.PeriodOverPeriodChangeResponseB\x17Z\x15go-grpc-backend/protob\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_analytics_proto_goTypes = []any{
	(*RatingCategory)(nil),                   // 0: analytics.RatingCategory
	(*CategoryScore)(nil),                    // 1: analytics.CategoryScore
	(*DailyAggregatedScoresResponse)(nil),    // 2: analytics.DailyAggregatedScoresResponse
	(*WeeklyAggregatedScoresResponse)(nil),   // 3: analytics.WeeklyAggregatedScoresResponse
	(*AggregatedCategoryScoresRequest)(nil),  // 4: analytics.AggregatedCategoryScoresRequest
	(*ScoresByTicketRequest)(nil),            // 5: analytics.ScoresByTicketRequest
	(*timestamppb.Timestamp)(nil),            // 6: google.protobuf.Timestamp
	(*OverallQualityScoreRequest)(nil),       // 7: analytics.OverallQualityScoreRequest
	(*PeriodOverPeriodChangeRequest)(nil),    // 8: analytics.PeriodOverPeriodChangeRequest
	(*AggregatedCategoryScoresResponse)(nil), // 9: analytics.AggregatedCategoryScoresResponse
	(*ScoresByTicketResponse)(nil),           // 10: analytics.ScoresByTicketResponse
	(*OverallQualityScoreResponse)(nil),      // 11: analytics.OverallQualityScoreResponse
	(*PeriodOverPeriodChangeResponse)(nil),   // 12: analytics.PeriodOverPeriodChangeResponse
}
var file_analytics_proto_depIdxs = []int32{
	6,  // 0: analytics.CategoryScore.date:type_name -> google.protobuf.Timestamp
	1,  // 1: analytics.DailyAggregatedScoresResponse.scores:type_name -> analytics.CategoryScore
	6,  // 2: analytics.DailyAggregatedScoresResponse.start_date:type_name -> google.protobuf.Timestamp
	6,  // 3: analytics.DailyAggregatedScoresResponse.end_date:type_name -> google.protobuf.Timestamp
	1,  // 4: analytics.WeeklyAggregatedScoresResponse.scores:type_name -> analytics.CategoryScore
	6,  // 5: analytics.WeeklyAggregatedScoresResponse.start_date:type_name -> google.protobuf.Timestamp
	6,  // 6: analytics.WeeklyAggregatedScoresResponse.end_date:type_name -> google.protobuf.Timestamp
	6,  // 7: analytics.AggregatedCategoryScoresRequest.start_date:type_name -> google.protobuf.Timestamp
	6,  // 8: analytics.AggregatedCategoryScoresRequest.end_date:type_name -> google.protobuf.Timestamp
	6,  // 9: analytics.ScoresByTicketRequest.start_date:type_name -> google.protobuf.Timestamp
	6,  // 10: analytics.ScoresByTicketRequest.end_date:type_name -> google.protobuf.Timestamp
	4,  // 11: analytics.AnalyticsService.GetAggregatedCategoryScores:input_type -> analytics.AggregatedCategoryScoresRequest
	5,  // 12: analytics.AnalyticsService.GetScoresByTicket:input_type -> analytics.ScoresByTicketRequest
	7,  // 13: analytics.AnalyticsService.GetOverallQualityScore:input_type -> analytics.OverallQualityScoreRequest
	8,  // 14: analytics.AnalyticsService.GetPeriodOverPeriodChange:input_type -> analytics.PeriodOverPeriodChangeRequest
	9,  // 15: analytics.AnalyticsService.GetAggregatedCategoryScores:output_type -> analytics.AggregatedCategoryScoresResponse
	10, // 16: analytics.AnalyticsService.GetScoresByTicket:output_type -> analytics.ScoresByTicketResponse
	11, // 17: analytics.AnalyticsService.GetOverallQualityScore:output_type -> analytics.OverallQualityScoreResponse
	12, // 18: analytics.AnalyticsService.GetPeriodOverPeriodChange:output_type -> analytics.PeriodOverPeriodChangeResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	file_category_score_proto_init()
	file_ticket_score_proto_init()
	file_overall_quality_score_proto_init()
	file_period_over_period_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
