// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: category_score.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Granularity int32

const (
	Granularity_GRANULARITY_UNSPECIFIED Granularity = 0
	Granularity_GRANULARITY_DAY         Granularity = 1
	Granularity_GRANULARITY_WEEK        Granularity = 2
)

// Enum value maps for Granularity.
var (
	Granularity_name = map[int32]string{
		0: "GRANULARITY_UNSPECIFIED",
		1: "GRANULARITY_DAY",
		2: "GRANULARITY_WEEK",
	}
	Granularity_value = map[string]int32{
		"GRANULARITY_UNSPECIFIED": 0,
		"GRANULARITY_DAY":         1,
		"GRANULARITY_WEEK":        2,
	}
)

func (x Granularity) Enum() *Granularity {
	p := new(Granularity)
	*p = x
	return p
}

func (x Granularity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Granularity) Descriptor() protoreflect.EnumDescriptor {
	return file_category_score_proto_enumTypes[0].Descriptor()
}

func (Granularity) Type() protoreflect.EnumType {
	return &file_category_score_proto_enumTypes[0]
}

func (x Granularity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Granularity.Descriptor instead.
func (Granularity) EnumDescriptor() ([]byte, []int) {
	return file_category_score_proto_rawDescGZIP(), []int{0}
}

type ScorePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Count         *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScorePoint) Reset() {
	*x = ScorePoint{}
	mi := &file_category_score_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScorePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScorePoint) ProtoMessage() {}

func (x *ScorePoint) ProtoReflect() protoreflect.Message {
	mi := &file_category_score_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScorePoint.ProtoReflect.Descriptor instead.
func (*ScorePoint) Descriptor() ([]byte, []int) {
	return file_category_score_proto_rawDescGZIP(), []int{0}
}

func (x *ScorePoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ScorePoint) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScorePoint) GetCount() *wrapperspb.Int32Value {
	if x != nil {
		return x.Count
	}
	return nil
}

type CategorySeries struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CategoryId         int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName       string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryTotalCount int32                  `protobuf:"varint,3,opt,name=category_total_count,json=categoryTotalCount,proto3" json:"category_total_count,omitempty"`
	Scores             []*ScorePoint          `protobuf:"bytes,4,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategorySeries) Reset() {
	*x = CategorySeries{}
	mi := &file_category_score_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySeries) ProtoMessage() {}

func (x *CategorySeries) ProtoReflect() protoreflect.Message {
	mi := &file_category_score_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySeries.ProtoReflect.Descriptor instead.
func (*CategorySeries) Descriptor() ([]byte, []int) {
	return file_category_score_proto_rawDescGZIP(), []int{1}
}

func (x *CategorySeries) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategorySeries) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategorySeries) GetCategoryTotalCount() int32 {
	if x != nil {
		return x.CategoryTotalCount
	}
	return 0
}

func (x *CategorySeries) GetScores() []*ScorePoint {
	if x != nil {
		return x.Scores
	}
	return nil
}

type BucketRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketRange) Reset() {
	*x = BucketRange{}
	mi := &file_category_score_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketRange) ProtoMessage() {}

func (x *BucketRange) ProtoReflect() protoreflect.Message {
	mi := &file_category_score_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketRange.ProtoReflect.Descriptor instead.
func (*BucketRange) Descriptor() ([]byte, []int) {
	return file_category_score_proto_rawDescGZIP(), []int{2}
}

func (x *BucketRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *BucketRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type AggregatedCategoryScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granularity   Granularity            `protobuf:"varint,1,opt,name=granularity,proto3,enum=analytics.Granularity" json:"granularity,omitempty"`
	BucketRange   *BucketRange           `protobuf:"bytes,2,opt,name=bucket_range,json=bucketRange,proto3" json:"bucket_range,omitempty"`
	Categories    []*CategorySeries      `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedCategoryScoresResponse) Reset() {
	*x = AggregatedCategoryScoresResponse{}
	mi := &file_category_score_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedCategoryScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedCategoryScoresResponse) ProtoMessage() {}

func (x *AggregatedCategoryScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_score_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedCategoryScoresResponse.ProtoReflect.Descriptor instead.
func (*AggregatedCategoryScoresResponse) Descriptor() ([]byte, []int) {
	return file_category_score_proto_rawDescGZIP(), []int{3}
}

func (x *AggregatedCategoryScoresResponse) GetGranularity() Granularity {
	if x != nil {
		return x.Granularity
	}
	return Granularity_GRANULARITY_UNSPECIFIED
}

func (x *AggregatedCategoryScoresResponse) GetBucketRange() *BucketRange {
	if x != nil {
		return x.BucketRange
	}
	return nil
}

func (x *AggregatedCategoryScoresResponse) GetCategories() []*CategorySeries {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_category_score_proto protoreflect.FileDescriptor

const file_category_score_proto_rawDesc = "" +
	"\n" +
	"\x14category_score.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x85\x01\n" +
	"\n" +
	"ScorePoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x121\n" +
	"\x05count\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05count\"\xb7\x01\n" +
	"\x0eCategorySeries\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x120\n" +
	"\x14category_total_count\x18\x03 \x01(\x05R\x12categoryTotalCount\x12-\n" +
	"\x06scores\x18\x04 \x03(\v2\x15.analytics.ScorePointR\x06scores\"m\n" +
	"\vBucketRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xd2\x01\n" +
	" AggregatedCategoryScoresResponse\x128\n" +
	"\vgranularity\x18\x01 \x01(\x0e2\x16.analytics.GranularityR\vgranularity\x129\n" +
	"\fbucket_range\x18\x02 \x01(\v2\x16.analytics.BucketRangeR\vbucketRange\x129\n" +
	"\n" +
	"categories\x18\x03 \x03(\v2\x19.analytics.CategorySeriesR\n" +
	"categories*U\n" +
	"\vGranularity\x12\x1b\n" +
	"\x17GRANULARITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fGRANULARITY_DAY\x10\x01\x12\x14\n" +
	"\x10GRANULARITY_WEEK\x10\x02B\x17Z\x15go-grpc-backend/protob\x06proto3"

var (
	file_category_score_proto_rawDescOnce sync.Once
	file_category_score_proto_rawDescData []byte
)

func file_category_score_proto_rawDescGZIP() []byte {
	file_category_score_proto_rawDescOnce.Do(func() {
		file_category_score_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_score_proto_rawDesc), len(file_category_score_proto_rawDesc)))
	})
	return file_category_score_proto_rawDescData
}

var file_category_score_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_category_score_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_category_score_proto_goTypes = []any{
	(Granularity)(0),                         // 0: analytics.Granularity
	(*ScorePoint)(nil),                       // 1: analytics.ScorePoint
	(*CategorySeries)(nil),                   // 2: analytics.CategorySeries
	(*BucketRange)(nil),                      // 3: analytics.BucketRange
	(*AggregatedCategoryScoresResponse)(nil), // 4: analytics.AggregatedCategoryScoresResponse
	(*timestamppb.Timestamp)(nil),            // 5: google.protobuf.Timestamp
	(*wrapperspb.Int32Value)(nil),            // 6: google.protobuf.Int32Value
}
var file_category_score_proto_depIdxs = []int32{
	5, // 0: analytics.ScorePoint.date:type_name -> google.protobuf.Timestamp
	6, // 1: analytics.ScorePoint.count:type_name -> google.protobuf.Int32Value
	1, // 2: analytics.CategorySeries.scores:type_name -> analytics.ScorePoint
	5, // 3: analytics.BucketRange.start:type_name -> google.protobuf.Timestamp
	5, // 4: analytics.BucketRange.end:type_name -> google.protobuf.Timestamp
	0, // 5: analytics.AggregatedCategoryScoresResponse.granularity:type_name -> analytics.Granularity
	3, // 6: analytics.AggregatedCategoryScoresResponse.bucket_range:type_name -> analytics.BucketRange
	2, // 7: analytics.AggregatedCategoryScoresResponse.categories:type_name -> analytics.CategorySeries
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_category_score_proto_init() }
func file_category_score_proto_init() {
	if File_category_score_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_score_proto_rawDesc), len(file_category_score_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_category_score_proto_goTypes,
		DependencyIndexes: file_category_score_proto_depIdxs,
		EnumInfos:         file_category_score_proto_enumTypes,
		MessageInfos:      file_category_score_proto_msgTypes,
	}.Build()
	File_category_score_proto = out.File
	file_category_score_proto_goTypes = nil
	file_category_score_proto_depIdxs = nil
}
