// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: overall_quality_score.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverallQualityScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverallQualityScoreRequest) Reset() {
	*x = OverallQualityScoreRequest{}
	mi := &file_overall_quality_score_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallQualityScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallQualityScoreRequest) ProtoMessage() {}

func (x *OverallQualityScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_overall_quality_score_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallQualityScoreRequest.ProtoReflect.Descriptor instead.
func (*OverallQualityScoreRequest) Descriptor() ([]byte, []int) {
	return file_overall_quality_score_proto_rawDescGZIP(), []int{0}
}

func (x *OverallQualityScoreRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *OverallQualityScoreRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type OverallQualityScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallScore  float32                `protobuf:"fixed32,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"` // Overall score as percentage (0-100)
	TotalRatings  int32                  `protobuf:"varint,2,opt,name=total_ratings,json=totalRatings,proto3" json:"total_ratings,omitempty"`  // Total number of ratings in the period
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverallQualityScoreResponse) Reset() {
	*x = OverallQualityScoreResponse{}
	mi := &file_overall_quality_score_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallQualityScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallQualityScoreResponse) ProtoMessage() {}

func (x *OverallQualityScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_overall_quality_score_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallQualityScoreResponse.ProtoReflect.Descriptor instead.
func (*OverallQualityScoreResponse) Descriptor() ([]byte, []int) {
	return file_overall_quality_score_proto_rawDescGZIP(), []int{1}
}

func (x *OverallQualityScoreResponse) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *OverallQualityScoreResponse) GetTotalRatings() int32 {
	if x != nil {
		return x.TotalRatings
	}
	return 0
}

func (x *OverallQualityScoreResponse) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *OverallQualityScoreResponse) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

var File_overall_quality_score_proto protoreflect.FileDescriptor

const file_overall_quality_score_proto_rawDesc = "" +
	"\n" +
	"\x1boverall_quality_score.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x1aOverallQualityScoreRequest\x129\n" +
	"\n" +
	"start_date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xd9\x01\n" +
	"\x1bOverallQualityScoreResponse\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x02R\foverallScore\x12#\n" +
	"\rtotal_ratings\x18\x02 \x01(\x05R\ftotalRatings\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDateB\x17Z\x15go-grpc-backend/protob\x06proto3"

var (
	file_overall_quality_score_proto_rawDescOnce sync.Once
	file_overall_quality_score_proto_rawDescData []byte
)

func file_overall_quality_score_proto_rawDescGZIP() []byte {
	file_overall_quality_score_proto_rawDescOnce.Do(func() {
		file_overall_quality_score_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_overall_quality_score_proto_rawDesc), len(file_overall_quality_score_proto_rawDesc)))
	})
	return file_overall_quality_score_proto_rawDescData
}

var file_overall_quality_score_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_overall_quality_score_proto_goTypes = []any{
	(*OverallQualityScoreRequest)(nil),  // 0: analytics.OverallQualityScoreRequest
	(*OverallQualityScoreResponse)(nil), // 1: analytics.OverallQualityScoreResponse
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
}
var file_overall_quality_score_proto_depIdxs = []int32{
	2, // 0: analytics.OverallQualityScoreRequest.start_date:type_name -> google.protobuf.Timestamp
	2, // 1: analytics.OverallQualityScoreRequest.end_date:type_name -> google.protobuf.Timestamp
	2, // 2: analytics.OverallQualityScoreResponse.start_date:type_name -> google.protobuf.Timestamp
	2, // 3: analytics.OverallQualityScoreResponse.end_date:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_overall_quality_score_proto_init() }
func file_overall_quality_score_proto_init() {
	if File_overall_quality_score_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_overall_quality_score_proto_rawDesc), len(file_overall_quality_score_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_overall_quality_score_proto_goTypes,
		DependencyIndexes: file_overall_quality_score_proto_depIdxs,
		MessageInfos:      file_overall_quality_score_proto_msgTypes,
	}.Build()
	File_overall_quality_score_proto = out.File
	file_overall_quality_score_proto_goTypes = nil
	file_overall_quality_score_proto_depIdxs = nil
}
