// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: period_over_period.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeriodOverPeriodChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentStart  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=current_start,json=currentStart,proto3" json:"current_start,omitempty"`
	CurrentEnd    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=current_end,json=currentEnd,proto3" json:"current_end,omitempty"`
	PreviousStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=previous_start,json=previousStart,proto3" json:"previous_start,omitempty"`
	PreviousEnd   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=previous_end,json=previousEnd,proto3" json:"previous_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodOverPeriodChangeRequest) Reset() {
	*x = PeriodOverPeriodChangeRequest{}
	mi := &file_period_over_period_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodOverPeriodChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodOverPeriodChangeRequest) ProtoMessage() {}

func (x *PeriodOverPeriodChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_period_over_period_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodOverPeriodChangeRequest.ProtoReflect.Descriptor instead.
func (*PeriodOverPeriodChangeRequest) Descriptor() ([]byte, []int) {
	return file_period_over_period_proto_rawDescGZIP(), []int{0}
}

func (x *PeriodOverPeriodChangeRequest) GetCurrentStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentStart
	}
	return nil
}

func (x *PeriodOverPeriodChangeRequest) GetCurrentEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentEnd
	}
	return nil
}

func (x *PeriodOverPeriodChangeRequest) GetPreviousStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PreviousStart
	}
	return nil
}

func (x *PeriodOverPeriodChangeRequest) GetPreviousEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PreviousEnd
	}
	return nil
}

type PeriodOverPeriodChangeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CurrentPeriodScore   float32                `protobuf:"fixed32,1,opt,name=current_period_score,json=currentPeriodScore,proto3" json:"current_period_score,omitempty"`      // Overall score for current period as percentage (0-100)
	PreviousPeriodScore  float32                `protobuf:"fixed32,2,opt,name=previous_period_score,json=previousPeriodScore,proto3" json:"previous_period_score,omitempty"`   // Overall score for previous period as percentage (0-100)
	ChangePercentage     float32                `protobuf:"fixed32,3,opt,name=change_percentage,json=changePercentage,proto3" json:"change_percentage,omitempty"`              // Percentage change from previous to current period
	CurrentTotalRatings  int32                  `protobuf:"varint,4,opt,name=current_total_ratings,json=currentTotalRatings,proto3" json:"current_total_ratings,omitempty"`    // Total ratings in current period
	PreviousTotalRatings int32                  `protobuf:"varint,5,opt,name=previous_total_ratings,json=previousTotalRatings,proto3" json:"previous_total_ratings,omitempty"` // Total ratings in previous period
	CurrentStart         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=current_start,json=currentStart,proto3" json:"current_start,omitempty"`
	CurrentEnd           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=current_end,json=currentEnd,proto3" json:"current_end,omitempty"`
	PreviousStart        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=previous_start,json=previousStart,proto3" json:"previous_start,omitempty"`
	PreviousEnd          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=previous_end,json=previousEnd,proto3" json:"previous_end,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PeriodOverPeriodChangeResponse) Reset() {
	*x = PeriodOverPeriodChangeResponse{}
	mi := &file_period_over_period_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodOverPeriodChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodOverPeriodChangeResponse) ProtoMessage() {}

func (x *PeriodOverPeriodChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_period_over_period_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodOverPeriodChangeResponse.ProtoReflect.Descriptor instead.
func (*PeriodOverPeriodChangeResponse) Descriptor() ([]byte, []int) {
	return file_period_over_period_proto_rawDescGZIP(), []int{1}
}

func (x *PeriodOverPeriodChangeResponse) GetCurrentPeriodScore() float32 {
	if x != nil {
		return x.CurrentPeriodScore
	}
	return 0
}

func (x *PeriodOverPeriodChangeResponse) GetPreviousPeriodScore() float32 {
	if x != nil {
		return x.PreviousPeriodScore
	}
	return 0
}

func (x *PeriodOverPeriodChangeResponse) GetChangePercentage() float32 {
	if x != nil {
		return x.ChangePercentage
	}
	return 0
}

func (x *PeriodOverPeriodChangeResponse) GetCurrentTotalRatings() int32 {
	if x != nil {
		return x.CurrentTotalRatings
	}
	return 0
}

func (x *PeriodOverPeriodChangeResponse) GetPreviousTotalRatings() int32 {
	if x != nil {
		return x.PreviousTotalRatings
	}
	return 0
}

func (x *PeriodOverPeriodChangeResponse) GetCurrentStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentStart
	}
	return nil
}

func (x *PeriodOverPeriodChangeResponse) GetCurrentEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentEnd
	}
	return nil
}

func (x *PeriodOverPeriodChangeResponse) GetPreviousStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PreviousStart
	}
	return nil
}

func (x *PeriodOverPeriodChangeResponse) GetPreviousEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PreviousEnd
	}
	return nil
}

var File_period_over_period_proto protoreflect.FileDescriptor

const file_period_over_period_proto_rawDesc = "" +
	"\n" +
	"\x18period_over_period.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x02\n" +
	"\x1dPeriodOverPeriodChangeRequest\x12?\n" +
	"\rcurrent_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fcurrentStart\x12;\n" +
	"\vcurrent_end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"currentEnd\x12A\n" +
	"\x0eprevious_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rpreviousStart\x12=\n" +
	"\fprevious_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vpreviousEnd\"\x9d\x04\n" +
	"\x1ePeriodOverPeriodChangeResponse\x120\n" +
	"\x14current_period_score\x18\x01 \x01(\x02R\x12currentPeriodScore\x122\n" +
	"\x15previous_period_score\x18\x02 \x01(\x02R\x13previousPeriodScore\x12+\n" +
	"\x11change_percentage\x18\x03 \x01(\x02R\x10changePercentage\x122\n" +
	"\x15current_total_ratings\x18\x04 \x01(\x05R\x13currentTotalRatings\x124\n" +
	"\x16previous_total_ratings\x18\x05 \x01(\x05R\x14previousTotalRatings\x12?\n" +
	"\rcurrent_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcurrentStart\x12;\n" +
	"\vcurrent_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"currentEnd\x12A\n" +
	"\x0eprevious_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rpreviousStart\x12=\n" +
	"\fprevious_end\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpreviousEndB\x17Z\x15go-grpc-backend/protob\x06proto3"

var (
	file_period_over_period_proto_rawDescOnce sync.Once
	file_period_over_period_proto_rawDescData []byte
)

func file_period_over_period_proto_rawDescGZIP() []byte {
	file_period_over_period_proto_rawDescOnce.Do(func() {
		file_period_over_period_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_period_over_period_proto_rawDesc), len(file_period_over_period_proto_rawDesc)))
	})
	return file_period_over_period_proto_rawDescData
}

var file_period_over_period_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_period_over_period_proto_goTypes = []any{
	(*PeriodOverPeriodChangeRequest)(nil),  // 0: analytics.PeriodOverPeriodChangeRequest
	(*PeriodOverPeriodChangeResponse)(nil), // 1: analytics.PeriodOverPeriodChangeResponse
	(*timestamppb.Timestamp)(nil),          // 2: google.protobuf.Timestamp
}
var file_period_over_period_proto_depIdxs = []int32{
	2, // 0: analytics.PeriodOverPeriodChangeRequest.current_start:type_name -> google.protobuf.Timestamp
	2, // 1: analytics.PeriodOverPeriodChangeRequest.current_end:type_name -> google.protobuf.Timestamp
	2, // 2: analytics.PeriodOverPeriodChangeRequest.previous_start:type_name -> google.protobuf.Timestamp
	2, // 3: analytics.PeriodOverPeriodChangeRequest.previous_end:type_name -> google.protobuf.Timestamp
	2, // 4: analytics.PeriodOverPeriodChangeResponse.current_start:type_name -> google.protobuf.Timestamp
	2, // 5: analytics.PeriodOverPeriodChangeResponse.current_end:type_name -> google.protobuf.Timestamp
	2, // 6: analytics.PeriodOverPeriodChangeResponse.previous_start:type_name -> google.protobuf.Timestamp
	2, // 7: analytics.PeriodOverPeriodChangeResponse.previous_end:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_period_over_period_proto_init() }
func file_period_over_period_proto_init() {
	if File_period_over_period_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_period_over_period_proto_rawDesc), len(file_period_over_period_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_period_over_period_proto_goTypes,
		DependencyIndexes: file_period_over_period_proto_depIdxs,
		MessageInfos:      file_period_over_period_proto_msgTypes,
	}.Build()
	File_period_over_period_proto = out.File
	file_period_over_period_proto_goTypes = nil
	file_period_over_period_proto_depIdxs = nil
}
